
POST http://localhost:4500/producto/Admin@Admin.com
Content-Type: application/json

{
  "token": {
    "token": "678d821c-d93f-4609-8214-f0721755587d"
  },
  "producto": {
    "codigoProducto": 123,
    "nombre": "Martillo de carpintero",
    "precio": 20.99,
    "descripcion": "Martillo de acero forjado",
    "stock": 100,
    "idHerramienta": {
      "id": 1,
      "tipoHerramienta": "Martillo",
      "idTipoProducto": {
        "id": 1,
        "tipo": "Herramienta"
      }
    },
    "idMarca": {
      "id": 2,
      "direccion": "Avenida Principal 456",
      "gmail": "info@marcamartillos.com",
      "nombre": "Herramientas Profesionales"
    }
  }
}



###
POST http://localhost:4500/herramienta/Admin@Admin.com
Content-Type: application/json

{
  "token": {
    "token": "678d821c-d93f-4609-8214-f0721755587d"
  },
  "herramienta": {
    "id": 1,
    "tipoHerramienta": "Martillo",
    "idTipoProducto": {
      "id": 1,
      "tipo": "Herramienta"
    }
  }
}



###
POST http://localhost:4500/user
Content-Type: application/json

{
  "pnombre": "John",
  "snombre": "William",
  "appaterno": "Doe",
  "apmaterno": "Smith",
  "gmail": "john.doe@example.com",
  "password": "secretpassword",
  "tipoUsuarioId": {
    "id" : 1,
    "tipo" : "Administrador"}
}


###
POST http://localhost:4500/marcaProducto/Admin@Admin.com
Content-Type: application/json

{
  "token": {
    "token": "678d821c-d93f-4609-8214-f0721755587d"
  },
  "marca": {
    "nombre": "Marca Ejemplo",
    "direccion": "Avenida Principal 123",
    "gmail": "info@marcaejemplo.com"
  }
}


###
POST http://localhost:4500/tipoProducto/Admin@Admin.com
Content-Type: application/json

{
  "token": {
    "token": "678d821c-d93f-4609-8214-f0721755587d"
  },
  "tipoProducto": {
    "tipo": "Mazo"
  }
}

###
POST http://localhost:4500/user/login
Content-Type: application/json

{
  "gmail": "gonzalez@example.com",
  "password": "contrasena"
}

